/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransitionRouteImport } from './routes/transition'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as Phase2RouteImport } from './routes/phase2'
import { Route as Phase1RouteImport } from './routes/phase1'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvaluationIdRouteImport } from './routes/evaluation.$id'
import { Route as EvaluationPhase2IdRouteImport } from './routes/evaluation.phase2.$id'
import { Route as EvaluationPhase1IdRouteImport } from './routes/evaluation.phase1.$id'

const TransitionRoute = TransitionRouteImport.update({
  id: '/transition',
  path: '/transition',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase2Route = Phase2RouteImport.update({
  id: '/phase2',
  path: '/phase2',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase1Route = Phase1RouteImport.update({
  id: '/phase1',
  path: '/phase1',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationIdRoute = EvaluationIdRouteImport.update({
  id: '/evaluation/$id',
  path: '/evaluation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationPhase2IdRoute = EvaluationPhase2IdRouteImport.update({
  id: '/evaluation/phase2/$id',
  path: '/evaluation/phase2/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationPhase1IdRoute = EvaluationPhase1IdRouteImport.update({
  id: '/evaluation/phase1/$id',
  path: '/evaluation/phase1/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/candidate': typeof CandidateRoute
  '/login': typeof LoginRoute
  '/phase1': typeof Phase1Route
  '/phase2': typeof Phase2Route
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transition': typeof TransitionRoute
  '/evaluation/$id': typeof EvaluationIdRoute
  '/evaluation/phase1/$id': typeof EvaluationPhase1IdRoute
  '/evaluation/phase2/$id': typeof EvaluationPhase2IdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/candidate': typeof CandidateRoute
  '/login': typeof LoginRoute
  '/phase1': typeof Phase1Route
  '/phase2': typeof Phase2Route
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transition': typeof TransitionRoute
  '/evaluation/$id': typeof EvaluationIdRoute
  '/evaluation/phase1/$id': typeof EvaluationPhase1IdRoute
  '/evaluation/phase2/$id': typeof EvaluationPhase2IdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/candidate': typeof CandidateRoute
  '/login': typeof LoginRoute
  '/phase1': typeof Phase1Route
  '/phase2': typeof Phase2Route
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transition': typeof TransitionRoute
  '/evaluation/$id': typeof EvaluationIdRoute
  '/evaluation/phase1/$id': typeof EvaluationPhase1IdRoute
  '/evaluation/phase2/$id': typeof EvaluationPhase2IdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/candidate'
    | '/login'
    | '/phase1'
    | '/phase2'
    | '/settings'
    | '/signup'
    | '/transition'
    | '/evaluation/$id'
    | '/evaluation/phase1/$id'
    | '/evaluation/phase2/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/candidate'
    | '/login'
    | '/phase1'
    | '/phase2'
    | '/settings'
    | '/signup'
    | '/transition'
    | '/evaluation/$id'
    | '/evaluation/phase1/$id'
    | '/evaluation/phase2/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/candidate'
    | '/login'
    | '/phase1'
    | '/phase2'
    | '/settings'
    | '/signup'
    | '/transition'
    | '/evaluation/$id'
    | '/evaluation/phase1/$id'
    | '/evaluation/phase2/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CandidateRoute: typeof CandidateRoute
  LoginRoute: typeof LoginRoute
  Phase1Route: typeof Phase1Route
  Phase2Route: typeof Phase2Route
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TransitionRoute: typeof TransitionRoute
  EvaluationIdRoute: typeof EvaluationIdRoute
  EvaluationPhase1IdRoute: typeof EvaluationPhase1IdRoute
  EvaluationPhase2IdRoute: typeof EvaluationPhase2IdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transition': {
      id: '/transition'
      path: '/transition'
      fullPath: '/transition'
      preLoaderRoute: typeof TransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase2': {
      id: '/phase2'
      path: '/phase2'
      fullPath: '/phase2'
      preLoaderRoute: typeof Phase2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase1': {
      id: '/phase1'
      path: '/phase1'
      fullPath: '/phase1'
      preLoaderRoute: typeof Phase1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/$id': {
      id: '/evaluation/$id'
      path: '/evaluation/$id'
      fullPath: '/evaluation/$id'
      preLoaderRoute: typeof EvaluationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/phase2/$id': {
      id: '/evaluation/phase2/$id'
      path: '/evaluation/phase2/$id'
      fullPath: '/evaluation/phase2/$id'
      preLoaderRoute: typeof EvaluationPhase2IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/phase1/$id': {
      id: '/evaluation/phase1/$id'
      path: '/evaluation/phase1/$id'
      fullPath: '/evaluation/phase1/$id'
      preLoaderRoute: typeof EvaluationPhase1IdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CandidateRoute: CandidateRoute,
  LoginRoute: LoginRoute,
  Phase1Route: Phase1Route,
  Phase2Route: Phase2Route,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TransitionRoute: TransitionRoute,
  EvaluationIdRoute: EvaluationIdRoute,
  EvaluationPhase1IdRoute: EvaluationPhase1IdRoute,
  EvaluationPhase2IdRoute: EvaluationPhase2IdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
